/*draw_text(x+20, y-20, "z : " + string(z))
draw_text(x+20, y, "bounce : " + string(bounce))
draw_text(x+20, y+20, "zspeed : " + string(zspeed))
draw_text(x+20, y+40, "bounced : " + string(bounce_count))
draw_text(x+20, y+60, "xyfriction : " + string(friction))